// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import 'dotenv/config';
import { defineConfig } from 'prisma/config';

const baseUrl = 'src/infrastructure/database/prisma';

export default defineConfig({
    schema: `${baseUrl}/schema.prisma`,
    migrations: {
        path: `${baseUrl}/migrations`,
    },
    datasource: {
        url: process.env['DATABASE_URL'],
    },
});
