export enum AuthErrorCode {
    INVALID_EMAIL = 'INVALID_EMAIL',
    WEAK_PASSWORD = 'WEAK_PASSWORD',

    USER_ALREADY_EXISTS = 'AUTH.USER_ALREADY_EXISTS',
    INVALID_CREDENTIALS = 'AUTH.INVALID_CREDENTIALS',
}
